### [build] 
apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    docker:
      target: runner
      cacheFrom:
        - docker.artifactory.liatr.io/liatrio/springtrader-builder:latest
        - docker.artifactory.liatr.io/liatrio/springtrader-runner:latest
  - image: sqlfdb 
    docker:
      target: sqlfdb
      cacheFrom:
        - docker.artifactory.liatr.io/liatrio/springtrader-builder:latest
        - docker.artifactory.liatr.io/liatrio/springtrader-runner:latest
  local: {}
### [build] 

### [deploy] 
deploy:
  helm:
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
<<<<<<< HEAD
        values:
          image: springtrader 
          sqlfdb: sqlfdb 

        ## Add the following 2 lines
        setValueTemplates:
          domain: "{{if .DOMAIN}}{{.DOMAIN}}{{else}}default{{end}}"

=======
        wait: true
        values:
          image: springtrader 
          sqlfdb: sqlfdb 
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
profiles:
- name: microk8s
  activation:
  - kubeContext: microk8s
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValues
    value: 
      storageClassName: microk8s-hostpath
<<<<<<< HEAD
### [deploy] 
=======
### [deploy] 
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
