apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtrader
  labels:
    app: springtrader
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: springtrader
  template:
    metadata:
      labels:
        app: springtrader
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-for-schema
        image: bitnami/kubectl:1.15
        args: ['wait','--for=condition=complete','job/generate-schema','--timeout=300s']
      containers:
      - name: springtrader
        image: {{ .Values.image }}
        env:
        - name: GROOVY_HOME
          value: '/usr/bin'
        livenessProbe:
          httpGet:
            path: /spring-nanotrader-web/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /spring-nanotrader-web/
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: rabbitmq
        image: rabbitmq
