<<<<<<< HEAD
=======
{{- if not (eq .Values.istioDomain "<no value>") -}}
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
<<<<<<< HEAD
    - {{ .Chart.Name }}.{{ .Values.domain | default "local" }}
=======
    - {{ .Chart.Name }}.{{ .Values.istioDomain }}
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
<<<<<<< HEAD
    - {{ .Chart.Name }}.{{ .Values.domain | default "local" }}
=======
    - {{ .Chart.Name }}.{{ .Values.istioDomain }}
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: "sds"
      privateKey: "sds"
      credentialName: "{{ .Release.Namespace }}-certificate"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
<<<<<<< HEAD
  - {{ .Chart.Name }}.{{ .Values.domain | default "local" }}
=======
  - {{ .Chart.Name }}.{{ .Values.istioDomain }}
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
  gateways:
  - "{{ .Chart.Name }}-gateway"
  http:
  - route:
    - destination:
<<<<<<< HEAD
        host: springtrader-app
        port:
          number: 8080
=======
        host: springtrader
        port:
          number: 8080
{{- end }}
>>>>>>> c54e117a9cfe155fe12497f758b7a46f80d915ee
