kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sqlf-server
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: {{ .Values.storageClassName | default "gp2" }}